name: CI

on:
  push:
    branches: [ main, metrics_ostream ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

  cmake_msvc_maintainer_test_stl_cxx20:
      name: CMake msvc (maintainer mode) with C++20
      runs-on: windows-latest
      steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
  
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: 'recursive'
      - name: setup
        run: |
          ./ci/setup_windows_ci_environment.ps1
      - name: run tests
        env:
          CXX_STANDARD: '20'
        run: ./ci/do_ci.ps1 cmake.maintainer.cxx20.stl.test
